server:
  capabilities:
    data_queries:
    - position
    - locations
    - items

collections:
  json:
    cache_dir: "etc/data/collections_cache/"

data:
  interface:
    name: "dummy"
    path: null