server:
  capabilities:
    data_queries:
    - locations
    - items
    - area
    - position
    - radius

collections:
  json:
    cache_dir: "etc/data/collections_cache/"

data:
  interface:
    fully_qualified_class_name: "edr_data_interface.dummy.dummy_interface.DummyEdrDataInterface"
