server:
  capabilities:
    data_queries:
    - locations
    - items

collections:
  json:
    cache_dir: "etc/data/collections_cache/"

data:
  interface:
    name: "2018_sunderland_fire"
    path: null